### ISSUE TITLE
default resolution

### ISSUE THREAD

**Issue by michaelneale** [cloudwalkio/omg-monitor#45]
@allanino  I think this is 2 (which seems reasonable default) and is overridable. However my question is if there is a downside to having it small for large numbers. Eg say you are learning network traffic in KB, numbers often in 20000 range etc - would a resolution of 2 be bad? I can't find documentation or mailling list information on the downside of having "too small" resolution (I understand too big means it may not spot things). Wanted to know if you had any knowledge on this?

**Comment by allanino** [comment]
In my experience, I found that too small resolutions (relative to input) lead to too much anomalies. So it's the opposite of the too big resolution you said: it will spot too many things.

We have two means by which we can control this. One is using a bigger resolution. The other is to use as input not the original data, but some transformation of it, like a moving average (average over a time window, like 30 minutes) or just some scaling (multiply the input by some scaling factor), or both. To use these transformations, just add  `moving_average_window: 30` and/or `scaling_factor: 0.5` to your parameters section in the YAML configuration. That's why we show three lines on the plots when using `debug=true`: we show actual input, transformed input and predicted value (based on transformed input). 

 The code for the transformations are here and below: https://github.com/cloudwalkio/omg-monitor/blob/3334fbf16774e04f7ab2e6b21823ce106c9d39ca/monitor/streams/base.py#L79

**Comment by michaelneale** [comment]
I added in some smoothing (this is for the dynamic monitor - which creates them on the fly) - and that helped a bit. Oddly it is noisy data like response time that is causing more problems now (I am just using a window of 10 entries to start). I am taking data from other systems, so am looking at a way to "estimate" the optimal resolution from an initial sampling of data before creating the monitor (as I don't think you can change it in the RandomDistributedScalarEncoder after it is created - which is a bit annoying as the scale can change, but the resolution can not). 

What do you use as scaling factors - say for a resolution of 2 - numbers in the range 0 - 1000 are good for that? 0-100? (I understand if varies with noise, but looking for some examples).

**Comment by michaelneale** [comment]
Can close this.
