### ISSUE TITLE
Nupic libraries not in container

### ISSUE THREAD

**Issue by MauricioRoman** [cloudwalkio/omg-monitor#52]
I installed the omg-monitor docker image but I do not see anywhere the nupic libraries inside, so it cannot instantiate the class Monitor().

**Comment by allanino** [comment]
Hi Mauricio.

I'll check it to see what's wrong. Probable some NuPIC update.

**Comment by allanino** [comment]
Hey @MauricioRoman, I think the problem is solved now.

It was related with a problem on NuPIC Docker image itself: https://github.com/numenta/nupic/issues/2721

After the fix on NuPIC I triggered a new build in our Docker Hub repo, so you can pull the new image to test.

Let me know if you still have problems.

**Comment by MauricioRoman** [comment]
Thank you Allan!

If I have problems I will reach out.

Mauricio

2015-11-03 5:48 GMT-08:00 Allan Costa <notifications@github.com>:

**Comment by MauricioRoman** [comment]
Hi Allan,

Truth is I have not been able to make the OMG-monitor work for the case
when one sends the data via HTTP. Using the tests, I send a metric {1,2}
repeatedly, with the same name, but it thinks it is a new metric each time.
I suspect some exception is triggered in the Model class. Since I am not
too conversant with Docker it is taking me much longer to debug.

Mauricio

2015-11-03 5:48 GMT-08:00 Allan Costa <notifications@github.com>:

**Comment by allanino** [comment]
Hi @MauricioRoman,

In fact I found a problem with the dynamical monitor, and I've fixed it. It was caused by the introduction of a new configuration parameter. This was the fix: https://github.com/cloudwalkio/omg-monitor/commit/d7284df531937fe7ab290c931518648ee607e28c

To help you debug your code, you can make use of the Makefile we have and run the command

```
make debug
```

This will rebuild the image and start services with logs in a `logs` folder. If you don't want to use the Makefile, just run the container container like this:

```
docker run -v $(PWD)/logs:/var/log/docker/monitor -e DYNAMIC=true -p 8080:8080 -p 5000:5000 cloudwalk/monitor
```

**Comment by MauricioRoman** [comment]
Hi Allan

Indeed I found the same problem, but since I was not handy with Docker I
spent a bunch of time to figure out how to get Exception printouts while
running stuff inside docker...finally found it as well!

So I have it up and running!

Mauricio

2015-11-05 7:12 GMT-08:00 Allan Costa <notifications@github.com>:

**Comment by allanino** [comment]
I'm glad to hear it worked, @MauricioRoman!
